lifeSenior/accounts/urls.py
from django.urls import path
from .views import home, signUp, logIn, logOut, profile, update_profile

app_name='accounts'

urlpatterns = [
    path('', home),
    path('signUp', signUp, name='signUp'),
    path('logIn', logIn, name='logIn'),
    path('logOut', logOut, name='logOut'),
    path('profile', profile, name="profile"),
    path('update_profile', update_profile, name="update_profile")
]
    

lifeSenior/lifeSenior/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from lifeSeniorApp.views import index, main


urlpatterns = [
    path('', index, name='index'),
    path('main', main, name='main'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('communication/', include('communicationApp.urls', namespace='communicationApp')),
    path('quiz/', include('quizApp.urls', namespace='quizApp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

lifeSenior/quizApp/urls.py
from django.urls import path
from .views import home, solveQuiz, studySpace, stateAll, stateCategory

app_name = 'quizApp'

urlpatterns = [
    path('home', home, name="home"),
    # path('solveQuiz/<int:quiz_id>/<str:choice_text>', solveQuiz, name="solveQuiz"),
    path('solveQuiz', solveQuiz, name="solveQuiz"),
    path('studySpace/<int:level>', studySpace, name="studySpace"),
    path('stateAll', stateAll, name='stateAll'),
    path('stateCategory', stateCategory, name="stateCategory")
]
    

lifeSenior/lifeSeniorApp/models.py
from django.db import models

# Create your models here.

lifeSenior/lifeSeniorApp/views.py
from django.shortcuts import render
from quizApp.models import Quiz
from communicationApp.models import Question

# Create your views here.
def index(request):
    return render(request, 'lifeSeniorApp/start.html')

def main(request):
    if request.method == 'POST':
        categoryArr = request.POST.getlist('array[]', None)
        
        categorys=[]
        for index in categoryArr:
            categorys.append(int(index))
        # sorts = ['date', 'likes', 'views', 'answerd', 'notAnswerd']

        print(categorys)

        index=0
        for category in categorys:
            if index==0:
                questions = Question.objects.filter(category=category)
            else:
                index+=1
                question = Question.objects.filter(category=category)
                questions.union(question)

        communication_list = questions.order_by('-date')[:10]
    else:
        communication_list = Question.objects.all().order_by('-date')[:10]

    def get_random():
        return Quiz.objects.order_by("?").first()

    randomQuiz = get_random()
    context = {
        'quiz': randomQuiz,
        'communication_list':communication_list
    }
    return render(request, 'lifeSeniorApp/main.html', context)

lifeSenior/templates/lifeSeniorApp/start.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>lifesenior</title>
    <link rel="stylesheet" href="{% static 'css/startStyle.css' %}">
</head>
<body>
    <!-- nav bar -->
    <!-- copy -->
    <nav>
        <div class="nav-left">
            <a href="{% url 'communicationApp:home' %}"><img src="{% static 'img/main-nav-logo.png' %}" alt="로고"></a>
            <a href="{% url 'index' %}" style="color: #FFFFFF;">인생선배</a>
        </div>
        <div class="nav-right">
            <a style="color: #FFFFFF;text-decoration: none;" href="{% url 'accounts:logIn' %}"><p>로그인</p></a>
        </div>
    </nav>

    <!-- header -->
    <header>
        <img src="{% static 'img/main-nav-logo.png' %}" alt="">
        <p>매일 하나씩 배워가는 인생조언</p>
        <p>어렵고 막막한 생활지식 배우기</p>
        <p>이제 인생선배를 통해 어른이 되어보아요.</p>
        <a href="{% url 'accounts:logIn' %}"><button>지금 시작하기</button></a>
    </header>
</body>
</html>