lifeSenior/accounts/urls.py
from django.urls import path
from .views import home, signUp, logIn, logOut, profile, update_profile

app_name='accounts'

urlpatterns = [
    path('', home),
    path('signUp', signUp, name='signUp'),
    path('logIn', logIn, name='logIn'),
    path('logOut', logOut, name='logOut'),
    path('profile', profile, name="profile"),
    path('update_profile', update_profile, name="update_profile")
]
    

lifeSenior/communicationApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home, communication_list, communication_detail, my_question, my_answer, question_create, answer_create, answer_list,test,getList, create_comment,getMyList,getAnswerList


app_name = 'communicationApp'

urlpatterns = [
    path('home', home, name="home"),
    path('communication_list', communication_list, name='communication_list'), #소통게시판 메인
    path('communication_detail/<int:question_id>', communication_detail, name='communication_detail'), #소통게시판 메인_질문하나 클릭하면 나오는 화면
    path('my_question', my_question, name='my_question'), #내가 한 질문
    path('my_answer', my_answer, name='my_answer'), #내가 한 답변
    path('question_create', question_create, name='question_create'), #질문하기_작성할때
    path('answer_create/<int:question_id>', answer_create, name='answer_create'), #답변하기_작성할때
    path('answer_list', answer_list, name='answer_list'), #답변하기_리스트
    path('test', test, name="test"),
    path('create_comment/<int:question_id>', create_comment, name="create_comment"),
    path('getList', getList, name="getList"),
    path('getMyList', getMyList, name="getMyList"),
    path('getAnswerList', getAnswerList, name="getAnswerList")
    
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

lifeSenior/lifeSenior/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from lifeSeniorApp.views import index, main


urlpatterns = [
    path('', index, name='index'),
    path('main', main, name='main'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('communication/', include('communicationApp.urls', namespace='communicationApp')),
    path('quiz/', include('quizApp.urls', namespace='quizApp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

lifeSenior/quizApp/urls.py
from django.urls import path
from .views import home, solveQuiz, studySpace, stateAll, stateCategory

app_name = 'quizApp'

urlpatterns = [
    path('home', home, name="home"),
    # path('solveQuiz/<int:quiz_id>/<str:choice_text>', solveQuiz, name="solveQuiz"),
    path('solveQuiz', solveQuiz, name="solveQuiz"),
    path('studySpace/<int:level>', studySpace, name="studySpace"),
    path('stateAll', stateAll, name='stateAll'),
    path('stateCategory', stateCategory, name="stateCategory")
]
    

lifeSenior/communicationApp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model

user = get_user_model()

#질문
class Question(models.Model):
    autor       = models.ForeignKey(user, on_delete=models.CASCADE, related_name='author_question') #작성자
    title       = models.CharField("TITLE", max_length=20, default="질문 제목") #질문 제목
    content     = models.TextField("CONTENT", max_length=300, default="질문 내용") #질문 내용
    #REALTY: 0, ECONOMY: 1, SELFDEVELOPMENT: 2, DISCOUNT: 3, COMMONSENSE: 4, ETC: 5
    date        = models.DateField("DATE", auto_now_add=True) #작성일자
    recommend   = models.PositiveIntegerField("RECOMMEND", default=0) #추천수
    category    = models.PositiveIntegerField("CATEGORY") #카테고리
    views       = models.PositiveIntegerField("VIEWS", default=0) #조회수
    answerd     = models.BooleanField("ANSWERD", default=False) #답변 여부
    

#질문에 대한 답변
class Answer(models.Model):
    question    = models.ForeignKey(Question, on_delete=models.CASCADE, default=1) #questionFK
    autor       = models.ForeignKey(user, on_delete=models.CASCADE, related_name='author_answer') #작성자
    content     = models.TextField("CONTENT", max_length=200, default="답변 내용") #답변 내용
    image       = models.ImageField("IMAGE", upload_to="questionAnswer/", default="static/img/defaultImg.png") #답변 사진
    recommend   = models.PositiveIntegerField("RECOMMEND", default=0) #추천수수집을 위한 모델

#댓글
class Comment(models.Model):
    autor       = models.ForeignKey(user, on_delete=models.CASCADE) #작성자
    question    = models.ForeignKey(Question, on_delete=models.CASCADE, default=1) #질문
    content     = models.CharField("CONTENT", max_length=20, default="댓글입력") #댓글 내용
    date        = models.DateField("DATE", auto_now_add=True) #작성 날짜

lifeSenior/communicationApp/forms.py
from django import forms
from models import Answer
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['title', 'content', 'photo', 'category']
        
    def __init__(self, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {
            'class': 'form-control', 
            #'placeholder': "제목 입력(4-100)",
            
        }
        self.fields['content'].widget.attrs = {
            'class': 'form-control', 
            #'placeholder': "내용 작성",
            'id': 'content',
            'rows':15,
        }
        self.fields['photo'].widget.attrs = {
            'class': 'form-control', 
            'placeholder': "사진 선택",
            'id': 'id_photo',
            'onchange' : 'loadFile(this)',
            'style': 'color:white;' # 알아서 색 맞춰 수정하기
        }
        self.fields['category'].widget.attrs = {
            'class': 'form-control', 
            'placeholder': "장르 선택",
            'id': 'id_genreName',
            # 'style': 'color:black;' # 알아서 색 맞춰 수정하기
        }
        

lifeSenior/communicationApp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Answer, Question, Comment

# Create your views here.
def home(request):
    return render(request, 'main.html')

def getList(request):
    categoryArr = request.POST.getlist('array[]', None)
    sort = request.POST.get('sort', None)
    categorys=[]
    for index in categoryArr:
        categorys.append(int(index)-1)
    # sorts = ['date', 'likes', 'views', 'answerd', 'notAnswerd']
    print(categorys)
    print(sort)
    index=0
    for category in categorys:
        if index==0:
            questions = Question.objects.filter(category=category)
        else:
            question = Question.objects.filter(category=category)
            questions = questions | question
        index += 1
    if sort == 'date':
        communication_list = questions.order_by('-date')
    elif sort == 'likes':
        communication_list = questions.order_by('-recommend')
    elif sort == 'views':
        communication_list = questions.order_by('-views')
    elif sort == 'answerd':
        communication_list = questions.filter(answerd=True).order_by('-date')
    else:
        communication_list = questions.filter(answerd=False).order_by('-date')

    # communication_list = Question.objects.all().order_by('-date')
    # print(communication_list)
    # print(questions)
    context = {
        'communication_list': communication_list,
    }
    return render(request, 'communicationApp/test.html', context)

def getMyList(request):
    categoryArr = request.POST.getlist('array[]', None)
    sort = request.POST.get('sort', None)
    categorys=[]
    for index in categoryArr:
        categorys.append(int(index)-1)
    # sorts = ['date', 'likes', 'views', 'answerd', 'notAnswerd']
    print(categorys)
    print(sort)
    index=0
    for category in categorys:
        if index==0:
            questions = Question.objects.filter(category=category, autor=request.user)
        else:
            question = Question.objects.filter(category=category, autor=request.user)
            questions.union(question)
        index+=1
    if sort == 'date':
        communication_list = questions.order_by('-date')
    elif sort == 'likes':
        communication_list = questions.order_by('-recommend')
    elif sort == 'views':
        communication_list = questions.order_by('-views')
    elif sort == 'answerd':
        communication_list = questions.filter(answerd=True).order_by('-date')
    else:
        communication_list = questions.filter(answerd=False).order_by('-date')

    # communication_list = Question.objects.all().order_by('-date')
    # print(communication_list)
    # print(questions)
    context = {
        'communication_list': communication_list,
    }
    return render(request, 'communicationApp/test.html', context)

def getAnswerList(request):
    categoryArr = request.POST.getlist('array[]', None)
    sort = request.POST.get('sort', None)
    categorys=[]
    for index in categoryArr:
        categorys.append(int(index)-1)
    # sorts = ['date', 'likes', 'views', 'answerd', 'notAnswerd']
    print(categorys)
    print(sort)
    index=0
    for category in categorys:
        if index==0:
            questions = Question.objects.filter(category=category, answerd=False).exclude(autor=request.user)
        else:
            question = Question.objects.filter(category=category, answerd=False).exclude(autor=request.user)
            questions.union(question)
        index+=1
    if sort == 'date':
        communication_list = questions.order_by('-date')
    elif sort == 'likes':
        communication_list = questions.order_by('-recommend')
    elif sort == 'views':
        communication_list = questions.order_by('-views')
    elif sort == 'answerd':
        communication_list = questions.filter(answerd=True).order_by('-date')
    else:
        communication_list = questions.filter(answerd=False).order_by('-date')

    # communication_list = Question.objects.all().order_by('-date')
    # print(communication_list)
    # print(questions)
    context = {
        'communication_list': communication_list,
    }
    return render(request, 'communicationApp/test.html', context)

#-----기본 메인 화면-----
#소통게시판 : communication_list
def communication_list(request):
    if request.method == 'POST':
        categoryArr = request.POST.getlist('array[]', None)
        sort = request.POST.get('sort', None)

        categorys=[]
        for index in categoryArr:
            categorys.append(int(index)-1)
        # sorts = ['date', 'likes', 'views', 'answerd', 'notAnswerd']

        print(categorys)
        print(sort)
        index=0
        for category in categorys:
            if index==0:
                questions = Question.objects.filter(category=category)
            else:
                question = Question.objects.filter(category=category)
                questions = questions | question
            index += 1

        if sort == 'date':
            communication_list = questions.order_by('-date')
        elif sort == 'likes':
            communication_list = questions.order_by('-recommend')
        elif sort == 'views':
            communication_list = questions.order_by('-views')
        elif sort == 'answerd':
            communication_list = questions.filter(answerd=True).order_by('-date')
        else:
            communication_list = questions.filter(answerd=False).order_by('-date')
    else:
        communication_list = Question.objects.all().order_by('-date')

    noQuestion = Question.objects.filter(answerd=False).exclude(autor=request.user).order_by("?")[:2]
    myQuestion = Question.objects.filter(autor=request.user).order_by("?")[:2]
    context = {
        'communication_list': communication_list,
        'noQuestion': noQuestion,
        'myQuestion': myQuestion,

    }
    return render(request, 'communicationApp/communication.html', context)

#소통게시판 메인_질문하나 클릭하면 나오는 화면 : communication_detail
def communication_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    category = question.category
    question.views += 1
    question.save()
    
    sameCategory = Question.objects.filter(category=category).exclude(pk=question_id).order_by("?")[:5]

    context = {
        'question': question,
        'sameCategory': sameCategory,
    }
    return render(request, 'communicationApp/question-detail.html', context)

#답변하기 : answer_list
def answer_list(request):
    if request.method == 'POST':
        categorys = [0, 1, 2, 3, 4, 5]
        # sorts = ['date', 'likes', 'views', 'answerd', 'notAnswerd']
        sort = 'date'

        index=0
        for category in categorys:
            if index==0:
                questions = Question.objects.filter(category=category, answerd=False).exclude(autor=request.user)
            else:
                index+=1
                question = Question.objects.filter(category=category, answerd=False).exclude(autor=request.user)
                questions.union(question)

        if sort == 'date':
            communication_list = questions.order_by('-date')
        elif sort == 'likes':
            communication_list = questions.order_by('-recommend')
        elif sort == 'views':
            communication_list = questions.order_by('-views')
        elif sort == 'answerd':
            communication_list = questions.filter(answerd=True).order_by('-date')
        else:
            communication_list = questions.filter(answerd=False).order_by('-date')
    else:
        communication_list = Question.objects.filter(answerd=False).exclude(autor=request.user).order_by("-date")
    context = {
        'communication_list': communication_list,
    }
    return render(request, 'communicationApp/answer.html', context)


#내가 한 질문 : my_question
def my_question(request):
    if request.method == 'POST':
        categorys = [0, 1, 2, 3, 4, 5]
        # sorts = ['date', 'likes', 'views', 'answerd', 'notAnswerd']
        sort = 'date'

        index=0
        for category in categorys:
            if index==0:
                questions = Question.objects.filter(category=category, autor=request.user)
            else:
                question = Question.objects.filter(category=category, autor=request.user)
                questions.union(question)
            index+=1

        if sort == 'date':
            communication_list = questions.order_by('-date')
        elif sort == 'likes':
            communication_list = questions.order_by('-recommend')
        elif sort == 'views':
            communication_list = questions.order_by('-views')
        elif sort == 'answerd':
            communication_list = questions.filter(answerd=True).order_by('-date')
        else:
            communication_list = questions.filter(answerd=False).order_by('-date')
    else:
        communication_list = Question.objects.filter(autor=request.user).order_by("-date")
    context = {
        'communication_list': communication_list,
    }
    return render(request, 'communicationApp/my-question.html', context)

#내가 한 답변 : my_answer
def my_answer(request):
    my_answer = Question.objects.all().order_by('-date')
    context = {
        'my_answer': my_answer
    }
    return render(request, 'communicationAPP/my_answer.html', context)

#질문하기 작성할 때 : question_create
def question_create(request):
    if request.method == 'POST':
        question = Question(autor=request.user,
                            title=request.POST['title'],
                            category=0,
                            content=request.POST['content'],)
        question.save()
        return redirect('communicationApp:communication_list')
    else:
        return render(request, 'communicationApp/question-create.html')

#답변하기 작성할 때 : answer_create
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':

lifeSenior/templates/communicationApp/answer-create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/communicationStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/questionCreateStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/questionDetailStyle.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <title>lifesenior</title>
    <style>
        #chooseFile {
        visibility: hidden;
    }       
    </style>
</head>

    <!-- nav bar -->
    <!-- copy -->
    <nav>
        <div class="nav-left">
            <img src="{% static 'img/main-nav-logo.png' %}" alt="로고">
            <a href="{% url 'main' %}" style="color: #95969D;">홈</a>
            <a style=" color: #95969D;" href="{% url 'quizApp:studySpace' level=0 %}">오늘의 공부</a>
            <a style=" color: #FFFFFF;" href="{% url 'communicationApp:communication_list' %}">소통 게시판</a>
        </div>
        <div class="nav-right">
            <a href="{% url 'accounts:profile' %}">
                <img class="nav-icon-third" style="margin-right: 15px;" src="{{request.user.profile.image.url}}" alt="">
            </a>
            <p style="color: #FFFFFF;top:50%;margin-bottom: 0px; margin-right:30px;
            color: var(--unnamed, #F6F7FB);
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;">{{request.user.profile.name}}님</p>
            <a href="{% url 'accounts:logOut' %}" style="text-decoration: none;
            color: inherit;">
            <p style="color: #FFFFFF;top:50%;margin-bottom: 0px; margin-right:40px;
            color: var(--1, #95969D);
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;">로그아웃</p>
            </a>
        </div>
    </nav>

        <!-- header -->
    <!-- copy -->
    <header class="study-title">
        <p>어른이 되기 위한 우리의</p>       
        <p>소통게시판</p>
    </header>
    <!-- header end -->

    <!-- nav2 -->
    <nav id="nav2">
        <a href="#" style="text-decoration: none;
        color: inherit;margin-right: 84px;"><p id="nav2-first" style="color: #FFFFFF;">질문하기</p></a>
        <a href="{% url 'communicationApp:my_question' %}" style="text-decoration: none;
        color: inherit;margin-right: 84px;"><p id="nav2-second" style="color:#95969D;">내가 한 질문</p></a>
        <a href="{% url 'communicationApp:answer_list' %}" style="text-decoration: none;
        color: inherit;color:#95969D;"><p>답변하기</p></a>
    </nav>

    <!-- main-scroll-icon -->
    <!-- copy -->
    <div class="main-scroll-icon">
        <img src="{% static 'img/main-scroll-icon.png' %}" alt="Scroll Icon">
    </div>
    <!-- main-scroll-icon end -->

    <!-- main-container -->
    <div style="margin-top: 92px;" id="main-container">
        <div class="quiz-note" style="margin-bottom: 270px;">
            <div class="score-container-text" id="sss">
                <img class="score-container-text-img" src="{% static 'img/main-nav-logo.png' %}" alt="">
                <div class="score-container-text-first">
                    <p class="score-container-text-highlight">{{question.autor.profile.name}}</p>
                    <p>님의&nbsp;</p>
                    <p class="score-container-text-highlight">질문</p>
                    <p>입니다.</p>
                </div>
            </div>
            <div class="quiz-note-box">
                <div class="quiz-note-box-top">
                    <div class="quiz-note-box-top-left">
                        <div class="quiz-note-box-top-first-top">
                            <p>Q. "{{question.title}}"</p>
                        </div>
                    </div>
                    <div class="quiz-note-box-top-right">
                        <div class="quiz-note-box-top-right-first">
                            <p>{{question.autor.profile.name}}</p>
                            <p>인생후배</p>
                        </div>
                        <div class="quiz-note-box-top-right-second">
                            <img src="{% static 'img/study-user-img.png' %}" alt="">
                        </div>
                    </div>       
                </div>
                <div class="quiz-note-box-bottom">
                    <div class="note-explain">
                        {{question.content}}
                    </div>
                    <div style="display: flex; flex-direction: column; justify-content: end;">
                        <hr>
                        <div style="display: flex; flex-direction: row; justify-content: space-between;">
                        {% if question.category == 0 %}
                        <p style="color: #F6F7FB; font-family: NanumGothic;font-size: 24px;font-style: normal;font-weight: 700;line-height: normal;border-radius: 22px;width: fit-content;padding: 10px;margin-left: 40px;margin-bottom: 30px;background-color: #FF5B16;">부동산</p>
                        {%elif question.category == 1 %}
                        <p style="color: #F6F7FB; font-family: NanumGothic;font-size: 24px;font-style: normal;font-weight: 700;line-height: normal;border-radius: 22px;width: fit-content;padding: 10px;margin-left: 40px;margin-bottom: 30px;background-color: #FF5B16;">경제</p>
                        {%elif question.category == 2 %}
                        <p style="color: #F6F7FB; font-family: NanumGothic;font-size: 24px;font-style: normal;font-weight: 700;line-height: normal;border-radius: 22px;width: fit-content;padding: 10px;margin-left: 40px;margin-bottom: 30px;background-color: #FF5B16;">트렌드</p>
                        {%elif question.category == 3 %}
                        <p style="color: #F6F7FB; font-family: NanumGothic;font-size: 24px;font-style: normal;font-weight: 700;line-height: normal;border-radius: 22px;width: fit-content;padding: 10px;margin-left: 40px;margin-bottom: 30px;background-color: #FF5B16;">할인</p>
                        {%elif question.category == 4 %}
                        <p style="color: #F6F7FB; font-family: NanumGothic;font-size: 24px;font-style: normal;font-weight: 700;line-height: normal;border-radius: 22px;width: fit-content;padding: 10px;margin-left: 40px;margin-bottom: 30px;background-color: #FF5B16;">시사</p>
                        {%else %}
                        <p style="color: #F6F7FB; font-family: NanumGothic;font-size: 24px;font-style: normal;font-weight: 700;line-height: normal;border-radius: 22px;width: fit-content;padding: 10px;margin-left: 40px;margin-bottom: 30px;background-color: #FF5B16;">기타</p>
                        {% endif %}
                        <p style="
                        color: #F6F7FB;
                        font-family: NanumGothic;
                        font-size: 24px;
                        font-style: normal;
                        font-weight: 700;
                        line-height: normal;
                        border-radius: 22px;
                        width: fit-content;
                        padding: 10px;
                        margin-left: 40px;
                        margin-bottom: 30px;
                        background-color: #FF5B16;
                        margin-right: 40px;"
                        >추천 {{question.recommend}}</p>
                        </div>
                        
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="top-text" style="margin-bottom: 123px; text-align: left;">
            <img style="width: 50.3px;
            height: 32.6px;" src="{% static 'img/main-nav-logo.png' %}" alt="">
            <div style="color: #17181A;
            font-family: NanumGothic;
            font-size: 32px;
            font-style: normal;
            font-weight: 700;
            line-height: 50px; /* 156.25% */
            display: flex;
            flex-direction: row;
            text-align: left;
            margin-top: 14px;
            width: 1180px;">
                <p style="color: #FF5B16;">나도 인생선배
                </p>
                <p >님에게&nbsp;</p>
                <p style="color: #FF5B16;">답변</p>
                <p>을 해보세요!</p>
            </div>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="text-box">
            <p class="box-title">답변 내용</p>
            <input style="height: 1099px;" type="text", name="content" placeholder="{{request.user.profile.name}}">
        </div> 
        <div class="text-box">
            <p class="box-title">이미지 업로드</p>
            <div class="img"></div>
                <div class="button" style="width: 180px;
                text-align: center;
                height: 70px;
                background-color: #FF5B16;
                color: #EBECF0;
                border-radius: 45px;
                padding: 20px;
                cursor: pointer;
                font-size: 17px;">
                    <label for="chooseFile">
                        이미지 업로드 버튼
                    </label>
                </div>
                <input class="imgUploadTag" type="file" id="chooseFile" name="answerImage" accept="image/*" onchange="loadFile(this)">
        </div> 
        <div style="display: flex;flex-direction: row;margin-top: 220px;justify-content: center;">
            <input type="submit" style="border-radius: 40px;
            background: #17181A;
            width: 180px;
            height: 80px;
            color: #F6F7FB;
            font-family: NanumGothic;
            font-size: 32px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;" value="업로드">
            <a href="{% url 'communicationApp:communication_detail' question.id %}" style="text-decoration: none;
            color: inherit;">
                <p style="border-radius: 40px;
                background: #EBECF0;
                width: 180px;
                height: 80px;
                color: #95969D;
                font-family: NanumGothic;
                font-size: 32px;
                font-style: normal;
                font-weight: 700;
                line-height: normal;
                text-align: center;
                padding-top: 12%;
                margin-left: 30px;">나가기</p>
            </a>
        </div>  
        </form> 
    </div>

    <!-- footer -->
    <footer>
        <img src="{% static 'img/footer.png' %}" alt="">
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>
        function loadFile(input) {
          var file = input.files[0];
          var name = document.getElementById('fileName');
          name.textContent = file.name;
        
          var newImage = document.createElement("img");
          newImage.setAttribute("class", 'img');
          newImage.src = URL.createObjectURL(file);
          newImage.style.width = "70%";
          newImage.style.height = "70%";
          newImage.style.visibility = "hidden";
          newImage.style.objectFit = "contain";
        
          var container = document.getElementById('image-show');
          container.appendChild(newImage);
        }
        
        var submit = document.querySelector('button[type="submit"]');
        submit.onclick = function(event) {
          event.preventDefault();
        
          var input = document.getElementById('chooseFile');
          var file = input.files[0];
        
          if (file) {
            var formData = new FormData();
            formData.append('answerImage', file);
            formData.append('content', document.querySelector('textarea[name="content"]').value);
            formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        
            var xhr = new XMLHttpRequest();
            xhr.open('POST', '{% url "communicationApp:answer_create" question.id %}');
            xhr.onload = function() {
              if (xhr.status === 200) {
                // 서버 응답이 성공적으로 도착한 경우 처리할 로직 작성
              }
            };
            xhr.send(formData);
          }
        };
        </script>
        
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="{% static 'js/scroll.js' %}"></script>
    <script src="{% static 'js/mainJs.js' %}"></script>
</body>
</html>

lifeSenior/templates/communicationApp/test.html
{% load static %}
{% for question in communication_list%}
<a href="{% url 'communicationApp:communication_detail' question.id%}" style="text-decoration: none; color: inherit;">
    <div class="community-box" >
        <div class="community-box-num">
            {% if question.answerd == False %}
                <p id="unanswer">Q</p>
            {% else %}
                <p id="answer">Q</p>
                <p>답변완료</p>
            {% endif %}
        </div>
        <div class="community-box-content">
            <p id="community-box-content-title">{{question.title}}</p>
            <p id="community-box-content-detail-content">{{question.content}}</p>
            <div class="community-box-content-footer">
                <div class="content-icon-box">
                    <div class="save">
                        <img src="{% static 'img/main-save-icon.png' %}" alt="">
                        <p>{{question.recommend}}</p>
                    </div>
                    <div class="saw">
                        <img src="{% static 'img/main-saw-icon.png' %}" alt="">
                        <p>{{question.views}}</p>
                    </div>
                    <div class="comment">
                        <img src="{% static 'img/main-comment-icon.png' %}" alt="">
                        <p>{{question.comment_set.count}}</p>
                    </div>
                </div>
                <div class="content-date">
                    <p>{{question.date}}</p>
                </div>
            </div>
        </div>
    </div>
</a>
{% endfor %}