lifeSenior/accounts/urls.py
from django.urls import path
from .views import home, signUp, logIn, logOut, profile, update_profile

app_name='accounts'

urlpatterns = [
    path('', home),
    path('signUp', signUp, name='signUp'),
    path('logIn', logIn, name='logIn'),
    path('logOut', logOut, name='logOut'),
    path('profile', profile, name="profile"),
    path('update_profile', update_profile, name="update_profile")
]
    

lifeSenior/communicationApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home, communication_list, communication_detail, my_question, my_answer, question_create, answer_create, answer_list,test,getList, create_comment,getMyList,getAnswerList


app_name = 'communicationApp'

urlpatterns = [
    path('home', home, name="home"),
    path('communication_list', communication_list, name='communication_list'), #소통게시판 메인
    path('communication_detail/<int:question_id>', communication_detail, name='communication_detail'), #소통게시판 메인_질문하나 클릭하면 나오는 화면
    path('my_question', my_question, name='my_question'), #내가 한 질문
    path('my_answer', my_answer, name='my_answer'), #내가 한 답변
    path('question_create', question_create, name='question_create'), #질문하기_작성할때
    path('answer_create/<int:question_id>', answer_create, name='answer_create'), #답변하기_작성할때
    path('answer_list', answer_list, name='answer_list'), #답변하기_리스트
    path('test', test, name="test"),
    path('create_comment/<int:question_id>', create_comment, name="create_comment"),
    path('getList', getList, name="getList"),
    path('getMyList', getMyList, name="getMyList"),
    path('getAnswerList', getAnswerList, name="getAnswerList")
    
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

lifeSenior/lifeSenior/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from lifeSeniorApp.views import index, main


urlpatterns = [
    path('', index, name='index'),
    path('main', main, name='main'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('communication/', include('communicationApp.urls', namespace='communicationApp')),
    path('quiz/', include('quizApp.urls', namespace='quizApp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

lifeSenior/quizApp/urls.py
from django.urls import path
from .views import home, solveQuiz, studySpace, stateAll, stateCategory

app_name = 'quizApp'

urlpatterns = [
    path('home', home, name="home"),
    # path('solveQuiz/<int:quiz_id>/<str:choice_text>', solveQuiz, name="solveQuiz"),
    path('solveQuiz', solveQuiz, name="solveQuiz"),
    path('studySpace/<int:level>', studySpace, name="studySpace"),
    path('stateAll', stateAll, name='stateAll'),
    path('stateCategory', stateCategory, name="stateCategory")
]
    

lifeSenior/quizApp/models.py
from django.db import models

# Create your models here.
class Quiz(models.Model):
    text = models.CharField("TEXT", max_length=100) # 질문 문항
    description = models.CharField("DESCRIPTION", max_length=40) # 카테고리 요약금
    category = models.PositiveIntegerField("CATEGORY") # 카테고리
    #REALTY: 0, ECONOMY: 1, SELFDEVELOPMENT: 2, DISCOUNT: 3, COMMONSENSE: 4, ETC: 5
    difficulty = models.PositiveIntegerField("DIFFICULTY", default=0) # 난이도
    total = models.PositiveIntegerField("TOTAL", default=0) # 전체 정답 시도 수
    incorrect = models.PositiveIntegerField("INCORRECT", default=0) # 문제 오답 수
    correct = models.CharField("CORRECT", max_length=10) # 문제의 정답
    content = models.TextField("CONTENT") # 오답노트



class Choice(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField("TEXT", max_length=10)
    isCorrect = models.CharField("ISCORRECT", max_length=10, default="incorrectA")

class Term(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=50)
    content = models.TextField("TEXT")
    category = models.CharField("CATEGORY", max_length=30)

lifeSenior/quizApp/views.py
from datetime import date
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Quiz
from accounts.models import Profile, CorrectByDate, InCorrectByDate
from .models import Term

# Create your views here.
def home(request):
    return render(request, 'quizApp/study-easy.html')

def solveQuiz(request):
    quiz_id = request.POST.get('pk', None) # ajax 통신을 통해서 template에서 POST방식으로 전달
    choice_text = request.POST.get('text', None)

    quiz = get_object_or_404(Quiz, pk=quiz_id)
    user = Profile.objects.get(user = request.user)

    if quiz.correct == choice_text:
        today = timezone.now().strftime('%Y-%m-%d')
        correct = CorrectByDate(user=request.user, date=today, quiz=quiz)
        correct.save()
        quiz.total += 1
        user.total += 1
        if quiz.category == "Realty":
            user.realty += 1
        elif quiz.category == "Economy":
            user.economy += 1
        elif quiz.category == "SelfDevelopment":
            user.selfDevelopment += 1
        elif quiz.category == "Discount":
            user.discount += 1
        elif quiz.category == "commonSense":
            user.commonSense += 1
        else:
            user.etc += 1
        quiz.save()
        user.save()
    else:
        today = timezone.now().strftime('%Y-%m-%d')
        inCorrect = InCorrectByDate(user=request.user, date=today, quiz=quiz)
        inCorrect.save()
        quiz.total += 1
        quiz.incorrect += 1
        quiz.save()

    # 이 전 페이지로 돌아가버리기
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))   

def studySpace(request, level):
    def get_random(category):
        term = Term.objects.filter(category=category).order_by("?").first()
        return term
    
    randomRealtyTerm = get_random("Realty")
    realtyContents = randomRealtyTerm.content.split("\n")
    randomEconomyTerm = get_random("Economy")
    economyContents = randomEconomyTerm.content.split("\n")

    quizs = {}
    quizAll = Quiz.objects.filter(difficulty=level).order_by("?").first()

    for category in range(6):
        quiz = Quiz.objects.filter(category=category, difficulty=level).order_by("?").first()
        boxIndex = category + 2
        boxNumber = "box-" + str(boxIndex)
        quizs[quiz] = boxNumber

    context = {
        'realtyTerm': randomRealtyTerm,
        'realtyContents': realtyContents,
        'economyTerm': randomEconomyTerm,
        'economyContents': economyContents,
        'quizs': quizs,
        'quizAll': quizAll
    }
    if level == 0:                    
        return render(request, 'quizApp/study-easy.html', context)
    elif level == 1:
        return render(request, 'quizApp/study-normal.html', context)
    elif level == 2:
        return render(request, 'quizApp/study-hard.html', context)
    else:
        return render(request, 'quizApp/study-very-hard.html', context)
    

def stateAll(request):
    today = date.today()
    
    inCorrectQuiz = InCorrectByDate.objects.filter(user=request.user, date=today)
    quizIds = inCorrectQuiz.values_list('quiz', flat=True).distinct()

    quizArr=[]
    for quizId in quizIds:
        quiz = Quiz.objects.get(pk=quizId)
        print(quiz)
        quizArr.append(quiz)
    print(quizArr)
    correctQuizCount = ""

    for index in range(6,0,-1):
        day = today - datetime.timedelta(days=index)
        correctQuiz = CorrectByDate.objects.filter(user=request.user, date=day)
        quizs = correctQuiz.values_list('quiz', flat=True).distinct()
        correctQuizCount += str(quizs.count())
    
    context = {
        'correctQuizCount': correctQuizCount,
        'quizs':quizArr
    }
    return render(request, 'quizApp/current-all.html', context)

def stateCategory(request):
    index = ""
    profile = Profile.objects.get(user = request.user)

    big = 0
    bigCategory=""

    small = 100000000
    smallCategory=""

    count={}
    
    index += str(profile.total // 10)
    index += str(profile.realty // 10)
    count['부동산']=profile.realty

    index += str(profile.economy // 10)
    count['경제']=profile.economy

    index += str(profile.selfDevelopment // 10)
    count['트렌드']=profile.selfDevelopment

    index += str(profile.discount // 10)
    count['할인']=profile.discount

    index += str(profile.commonSense // 10)
    count['시사상식']=profile.commonSense

    index += str(profile.etc // 10)
    count['기타']=profile.etc

    for key, value in count.items():
        if big <= value:
            big = value
            bigCategory = key
        if small >= value:
            small=value
            smallCategory = key


    print(bigCategory)
    print(smallCategory)

    context = {
        'index': index,
        'bigCategory': bigCategory,
        'smallCategory': smallCategory,
    }
    return render(request, 'quizApp/current-not-all.html', context)

lifeSenior/templates/quizApp/current-not-all.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>lifesenior</title>
    <link rel="stylesheet" href="{% static 'css/studyStyle.css' %}">
</head>
<body>
    <!-- nav bar -->
    <!-- copy -->
    <nav>
        <div class="nav-left">
            <img src="{% static 'img/main-nav-logo.png' %}" alt="로고">
            <a href="./main.html" style=" color: #95969D;" >홈</a>
            <a class="nav-second" style="color: #FFFFFF;" href="{% url 'quizApp:studySpace' level=0 %}">오늘의 공부</a>
            <a class="nav-third" href="{% url 'communicationApp:communication_list' %}" style=" color: #95969D;">소통 게시판</a>
        </div>
        <div class="nav-right">
            <a href="{% url 'accounts:profile' %}">
                <img class="nav-icon-third" style="margin-right: 15px;" src="{{request.user.profile.image.url}}" alt="">
            </a>
            <p style="color: #FFFFFF;top:50%;margin-bottom: 0px; margin-right:30px;
            color: var(--unnamed, #F6F7FB);
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;">{{request.user.profile.name}}님</p>
            <a href="{% url 'accounts:logOut' %}" style="text-decoration: none;
            color: inherit;">
            <p style="color: #FFFFFF;top:50%;margin-bottom: 0px; margin-right:40px;
            color: var(--1, #95969D);
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;">로그아웃</p>
        </a>
        </div>
    </nav>
    <!-- nav bar end -->

    <!-- header -->
    <!-- copy -->
    <header class="study-title">
        <p>어른이 되기 위한 우리의</p>       
        <p>오늘의 공부</p>
    </header>
    <!-- header end -->

    <!-- nav2 -->
    <nav id="nav2">
        <a href="{% url 'quizApp:studySpace' level=0 %}" style="text-decoration: none;
        color: inherit;"><p id="nav2-first">학 습 공 간</p></a>
        <a href="{% url 'quizApp:stateCategory' %}" style="text-decoration: none;
        color: inherit;"><p id="nav2-second" style="color: #F6F7FB;">현 황</p></a>
    </nav>

    <!-- main-scroll-icon -->
    <!-- copy -->
    <div class="main-scroll-icon">
        <img src="{% static 'img/main-scroll-icon.png' %}" alt="Scroll Icon">
    </div>
    <!-- main-scroll-icon end -->

    <!-- 현황 페이지 -->
    <div id="current-situation">
        <div class="score-container">
            <div class="score-container-text" id="ss">
                <img class="score-container-text-img" src="{% static 'img/main-nav-logo.png' %}" alt="">
                <div class="score-container-text-first">
                    <p>안녕하세요!&nbsp;</p>
                    <p class="score-container-text-highlight">부기&nbsp;</p>
                    <p>후배님</p>
                </div>
                <div class="score-container-text-second">
                    <p class="score-container-text-highlight">부기&nbsp;</p>
                    <p>후배님의&nbsp;</p>
                    <p>성적이&nbsp;</p>
                    <p>오르고 있군요!</p>
                </div>
                <div class="score-container-text-third">
                    <p>특히&nbsp;</p>
                    <p class="score-container-text-highlight">{{bigCategory}}</p>
                    <p>분야의&nbsp;</p>
                    <p>성적이 가장 좋습니다!</p>
                </div>
                <!-- <div class="not-all-score-conatiner-text-second">
                    <p>부기&nbsp;</p>
                    <p>후배님의 공부현황을 확인하세요</p>
                </div> -->
            </div>
            <p style="color: #17181A;
            font-size: 32px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;" 
            >점수 통계</p>
            <div class="score-box">
                <div class="score-box-nav">
                    <a href="{% url 'quizApp:stateAll' %}" style="text-decoration: none;
                    color: inherit;"><p id="nav-all-score">전체 점수</p></a>
                    <a href="{% url 'quizApp:stateCategory' %}" style="text-decoration: none;
                    color: inherit;"><p id="nav-not-all-score" style="
                    color: #17181A; border-bottom: 3px solid #FF5B16;">항목별 점수</p></a>
                    
                </div>
                <div class="score-graph" id="not-all-score">
                    <div class="score-graph-count">
                        <p>100</p>
                        <p>80</p>
                        <p>60</p>
                        <p>40</p>
                        <p>20</p>
                        <p>0</p>
                    </div>
                    <div class="score-graph-view-box">
                        <div class="score-graph-view">
                            <div class="score-graph-body" id="not-all-score-body">
                            </div>
                            <div class="score-graph-date">
                                <p>전체</p>
                            </div>
                        </div>
                        <div class="score-graph-view">
                            <div class="score-graph-body" id="not-all-score-body">
                            </div>
                            <div class="score-graph-date">
                                <p>부동산</p>
                            </div>
                        </div>
                        <div class="score-graph-view">
                            <div class="score-graph-body" id="not-all-score-body">
                            </div>
                            <div class="score-graph-date">
                                <p>경제</p>
                            </div>
                        </div>
                        <div class="score-graph-view">
                            <div class="score-graph-body" id="not-all-score-body">
                            </div>
                            <div style="display: flex; flex-direction: column;" class="score-graph-date">
                                <p>트렌드</p>
                                <!-- <p>자기계발</p> -->
                            </div>
                        </div>
                        <div class="score-graph-view">
                            <div class="score-graph-body" id="not-all-score-body">
                            </div>
                            <div class="score-graph-date">
                                <p>할인</p>
                            </div>
                        </div>
                        <div class="score-graph-view">
                            <div class="score-graph-body" id="not-all-score-body">
                            </div>
                            <div class="score-graph-date">
                                <p>시사상식</p>
                            </div>
                        </div>
                        <div class="score-graph-view">
                            <div class="score-graph-body" id="not-all-score-body">
                            </div>
                            <div class="score-graph-date">
                                <p>기타</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div style="margin-top: 102px;" class="not-all-score-container-footer-text">
                <img class="score-container-text-img" src="{% static 'img/main-nav-logo.png' %}" alt="">
                <div class="not-all-score-container-text-first">
                    <p class="score-container-text-highlight">{{smallCategory}}&nbsp;</p>
                    <p>분야의 정답률이&nbsp;</p>
                    <p class="score-container-text-highlight">저조</p>
                    <p>해요.</p>
                </div>
                <div class="not-all-score-container-text-second">
                    <p>오늘은&nbsp;</p>
                    <p class="score-container-text-highlight">{{smallCategory}}&nbsp;</p>
                    <p>분야의 정보를 살펴보는 것은 어떤가요?</p>
                </div>
            </div>
        </div>
    </div>
    <div id="category" name={{ index }}></div>
    <!-- footer -->
    <!-- copy -->
    <footer>
        <img src="{% static 'img/footer.png' %}" alt="">
    </footer>
    <!-- footer end -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="{% static 'js/scroll.js' %}"></script>
    <script src="{% static 'js/studyJs.js' %}"></script>
</body>
</html>

lifeSenior/templates/quizApp/study-easy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>lifesenior</title>
    <link rel="stylesheet" href="{% static 'css/studyStyle.css' %}">
    <!-- <link rel="stylesheet" href="../../static/css/studyStyle.css"> -->
</head>
<body onload="handleScrollPosition(event)">
    <!-- nav bar -->
    <!-- copy -->
    <nav>
        <div class="nav-left">
            <img src="{% static 'img/main-nav-logo.png' %}" alt="로고">
            <a href="{% url 'main' %}" style=" color: #95969D;" >홈</a>
            <a class="nav-second" style="color: #FFFFFF;" href="{% url 'quizApp:studySpace' level=0 %}">오늘의 공부</a>
            <a class="nav-third" href="{% url 'communicationApp:communication_list' %}" style=" color: #95969D;">소통 게시판</a>
        </div>
        <div class="nav-right">
            <a href="{% url 'accounts:profile' %}">
                <img class="nav-icon-third" style="margin-right: 15px;" src="{{request.user.profile.image.url}}" alt="">
            </a>
            <p style="color: #FFFFFF;top:50%;margin-bottom: 0px; margin-right:30px;
            color: var(--unnamed, #F6F7FB);
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;">{{request.user.profile.name}}님</p>
            <a href="{% url 'accounts:logOut' %}" style="text-decoration: none;
            color: inherit;">
            <p style="color: #FFFFFF;top:50%;margin-bottom: 0px; margin-right:40px;
            color: var(--1, #95969D);
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;">로그아웃</p>
            </a>
    </nav>
    <!-- nav bar end -->

    <!-- header -->
    <!-- copy -->
    <header class="study-title">
        <p>어른이 되기 위한 우리의</p>       
        <p>오늘의 공부</p>
    </header>
    <!-- header end -->

    <!-- nav2 -->
    <nav id="nav2">
        <a href="{% url 'quizApp:studySpace' level=2%}" style="text-decoration: none;
        color: inherit;"><p id="nav2-first" style="color: #F6F7FB; ">학 습 공 간</p></a>
        <a href="{% url 'quizApp:stateAll' %}" style="text-decoration: none;
        color: inherit;"><p id="nav2-second">현 황</p></a>
    </nav>

    <!-- main-scroll-icon -->
    <!-- copy -->
    <div class="main-scroll-icon">
        <img src="{% static 'img/main-scroll-icon.png' %}" alt="Scroll Icon">
    </div>
    <!-- main-scroll-icon end -->

    <!-- 학습공간 페이지 -->
    <div id="study-place">
        <div class="advice-box">
            <div class="speech-bubble-box">
                <div class="speech-bubble">
                    <img src="{% static 'img/study-logo.png' %}" alt="">
                    <div class="speech-bubble-content">
                        <div id="speech-bubble-content-first">
                            <p>오늘은&nbsp;</p>
                            <p id="speech-bubble-content-date1">7</p>
                            <p>일째 공부중</p>
                        </div>
                        <div id="speech-bubble-content-second">
                            <p>인생선배의&nbsp;</p>
                            <p id="speech-bubble-content-date2">6월 12일</p>
                            <p>&nbsp;</p>
                            <p>조언</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="today-first-box">
                <p class="today-box-title">오늘의 부동산 용어</p>
                <div class="today-study-box">
                    <p class="today-study-box-title">이것만은 알고가자 부동산 용어</p>
                    <div class="today-study-box-word">
                        <p><strong>{{ realtyTerm.title }}</strong>: {{ realtyTerm.description }}</p>
                    </div>
                    <div class="today-study-box-info" style="text-align:center;">
                        {% for content in realtyContents%}
                        <p>{{ content }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="today-second-box">
                <p class="today-box-title">오늘의 경제 용어</p>
                <div class="today-study-box">
                    <p class="today-study-box-title">이것만은 알고가자 경제 용어</p>
                    <div class="today-study-box-word">
                        <p><strong>{{ economyTerm.title }}</strong>: {{ economyTerm.description}}</p>
                    </div>
                    <div class="today-study-box-info" style="text-align:center;">
                        {% for content in economyContents %}
                        <p>{{ content }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="quiz-container">
            <div class="quiz-container-title">
                <img src="{% static 'img/main-nav-logo.png' %}" alt="">
                <p>퀴즈를 풀어보아요!</p>
                <p>내 수준에 맞는 난이도를 선책하고 퀴즈를 풀어보세요.</p>
            </div>
            <div class="quiz-level-container">
                <a href="{% url 'quizApp:studySpace' level=0 %}" style="text-decoration: none;
                color: inherit;"  onclick="handleScrollPosition(event)">
                    <div class="quiz-level-box" style="background-color: #17181A;" >
                        <p class="quiz-level-comment" style="color: #F6F7FB;">많은 조언을 얻었나요?</p>
                        <div class="quiz-level">
                            <p class="quiz-level-name"style="color: #F6F7FB;">쉬움</p>
                            <img src="{% static 'img/study-easy.png' %}" alt="">
                        </div>
                    </div>
                </a>
                <a href="{% url 'quizApp:studySpace' level=1 %}" style="text-decoration: none;
                color: inherit;"  onclick="handleScrollPosition(event)">
                    <div class="quiz-level-box">
                        <p class="quiz-level-comment">많은 조언을 얻었나요?</p>
                        <div class="quiz-level">
                            <p class="quiz-level-name">보통</p>
                            <img src="{% static 'img/study-normal.png' %}" alt="">
                        </div>
                    </div>
                </a>
                <a href="{% url 'quizApp:studySpace' level=2 %}" style="text-decoration: none;
                color: inherit;" onclick="handleScrollPosition(event)">
                    <div class="quiz-level-box" >
                        <p class="quiz-level-comment" >많은 조언을 얻었나요?</p>
                        <div class="quiz-level">
                            <p class="quiz-level-name" >어려움</p>
                            <img src="{% static 'img/study-hard.png' %}" alt="">
                        </div>
                    </div>
                </a>
                <a href="{% url 'quizApp:studySpace' level=3 %}" style="text-decoration: none;
                color: inherit;" onclick="handleScrollPosition(event)">
                    <div class="quiz-level-box">
                        <p class="quiz-level-comment">많은 조언을 얻었나요?</p>
                        <div class="quiz-level">
                            <p class="quiz-level-name">아주 어려움</p>
                            <img src="{% static 'img/study-very-hard.png' %}" alt="">
                        </div>
                    </div>
                </a>
            </div>
            <p class="quiz-container-p">오늘 배운 내용을 복습해 봅시다.</p>
            <div class="quiz-box">
                <div class="quiz-box-content">
                    <p class="quiz-box-content-title">1일 1퀴즈</p>
                    <div class="quiz-box-content-nav">
                        <p id="p-1">전체</p>
                        <p id="p-2">부동산</p>
                        <p id="p-3">경제</p>
                        <p id="p-4">트렌드</p>
                        <p id="p-5">할인</p>
                        <p id="p-6">시사상식</p>
                        <p id="p-7">기타</p>
                    </div>
                    <div class="quiz-change-box" id="box-1">
                        <p class="quiz-box-content-p-fisrt">{{ quizAll.text }}</p>
                        <p class="quiz-box-content-p-second">{{ quizAll.description }}</p>
                        <div class="quiz-box-content-quizBtn">
                            {% for choice in quizAll.choice_set.all %}
                                <input type="submit" class="quiz-select-btn {{choice.isCorrect}}" name="{{quiz.id}}" value="{{choice.text}}"{% if forloop.last %}style="margin-right: 0;"{% endif %}>
                            {% endfor %}
                        </div>
                    </div>
                    {% for quiz, id in quizs.items %}
                        <div class="quiz-change-box" id="{{ id }}">
                            <p class="quiz-box-content-p-fisrt">{{ quiz.text }}</p>
                            <p class="quiz-box-content-p-second">{{ quiz.description }}</p>
                            <div class="quiz-box-content-quizBtn">
                                {% for choice in quiz.choice_set.all %}
                                <input type="submit" class="quiz-select-btn {{choice.isCorrect}}" name="{{quiz.id}}" value="{{choice.text}}"{% if forloop.last %}style="margin-right: 0;"{% endif %}>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <img class="study-next-btn" src="{% static 'img/study-next-btn.png' %}" alt="">
                <div class="quiz-overlay"></div>
                <div class="quiz-correct-modal">
                    <p class="quiz-correct-modal-content">정답이에요!</p>
                    <img src="{% static 'img/correct.png' %}" alt="">
                    <p class="quiz-modal-content">완벽히 이해했군요! 다음 퀴즈도 풀어보세요!</p>
                </div>
                <div class="quiz-incorrect-modal">
                    <p class="quiz-incorrect-modal-content">틀렸어요,,!</p>
                    <img src="{% static 'img/incorrect.png' %}" alt="">
                    <p class="quiz-modal-content">완벽히 이해했군요! 다음 퀴즈도 풀어보세요!</p>
                </div>
            </div>
        </div>
    </div>
    <!-- footer -->
    <!-- copy -->
    <footer>
        <img src="{% static 'img/footer.png' %}" alt="">
    </footer>
    <!-- footer end -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(".quiz-select-btn").click(function(){
            var pk = $(this).attr('name')
            var text = $(this).attr('value')
            $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
                type: "POST", // 데이터를 전송하는 방법을 지정
                url: "{% url 'quizApp:solveQuiz' %}", // 통신할 url을 지정
                data: {'pk': pk, 'text': text, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
                dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
                // 서버측에서 전송한 Response 데이터 형식 (json)
                // {'likes_count': post.like_count, 'message': message }
                success: function(response){ // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경
                    console.log("success")
                },
                error: function(request, status, error){ // 통신 실패시 - 로그인 페이지 리다이렉트  
                    console.log("fail")
                },
            });
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="{% static 'js/scroll.js' %}"></script>
    <script src="{% static 'js/studyJs.js' %}"></script>
</body>
</html>